package org.easyubl.models;

import java.util.List;

public interface CompanyProvider {

    /**
     * @param name       name of the space
     * @param user       owner of space, if the space don't have owner user can be null
     * @return created space
     */
    CompanyModel addCompany(String name, UserModel user);

    /**
     * Find space by id
     *
     * @param id identity auto generated by the system
     * @return space, is not found return null
     */
    CompanyModel getCompany(String id);

    /**
     * @param company space to be removed
     * @return true if operation is success
     */
    boolean removeCompany(CompanyModel company);

    /**
     * @param user owner
     * @return spaces owned by user
     */
    List<CompanyModel> getCompanies(UserModel user);

    /**
     * @param user   owner
     * @param offset offset
     * @param limit  limit
     * @return spaces owned by user
     */
    List<CompanyModel> getCompanies(UserModel user, int offset, int limit);

}
